/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Referrals Route */
        get: operations["list_referrals_route_referrals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referral Route */
        get: operations["get_referral_route_referrals__referral_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Status Route */
        patch: operations["update_status_route_referrals__referral_id__status_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Field */
            field?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Duplicate Count */
            duplicate_count: number;
        };
        /**
         * PatientName
         * @description Best-effort split of whatever name shape the source used.
         *
         *     `raw_full_name` is always populated -- it's what we display and search
         *     on. `first_name`/`last_name` are Optional because splitting "GRACE
         *     DELACROIX" or "RENTERIA, MARGUERITE" into parts is a heuristic, not a
         *     guarantee, and callers must not assume it always succeeded.
         */
        PatientName: {
            /** Raw Full Name */
            raw_full_name: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** Referral */
        Referral: {
            /** Id */
            id: string;
            source: components["schemas"]["ReferralSource"];
            /** Source Record Id */
            source_record_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            patient_name: components["schemas"]["PatientName"];
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Referring Provider */
            referring_provider?: string | null;
            /** Reason */
            reason?: string | null;
            urgency: components["schemas"]["Urgency"];
            /** @default new */
            status: components["schemas"]["ReferralStatus"];
            /** Duplicate Group Id */
            duplicate_group_id?: string | null;
            /** Possible Duplicate */
            readonly possible_duplicate: boolean;
        };
        /** ReferralDetail */
        ReferralDetail: {
            /** Id */
            id: string;
            source: components["schemas"]["ReferralSource"];
            /** Source Record Id */
            source_record_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            patient_name: components["schemas"]["PatientName"];
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Referring Provider */
            referring_provider?: string | null;
            /** Reason */
            reason?: string | null;
            urgency: components["schemas"]["Urgency"];
            /** @default new */
            status: components["schemas"]["ReferralStatus"];
            /** Duplicate Group Id */
            duplicate_group_id?: string | null;
            /** Duplicate Group */
            duplicate_group?: components["schemas"]["ReferralSummary"][];
            /** Possible Duplicate */
            readonly possible_duplicate: boolean;
        };
        /** ReferralDetailResponse */
        ReferralDetailResponse: {
            data: components["schemas"]["ReferralDetail"];
        };
        /** ReferralListResponse */
        ReferralListResponse: {
            /** Data */
            data: components["schemas"]["Referral"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * ReferralSource
         * @enum {string}
         */
        ReferralSource: "efax" | "ehr_fhir" | "web_form";
        /**
         * ReferralStatus
         * @enum {string}
         */
        ReferralStatus: "new" | "in_review" | "accepted" | "rejected" | "scheduled";
        /**
         * ReferralSummary
         * @description Lightweight referral shape used inside another referral's duplicate group.
         *
         *     Deliberately not the full `Referral` -- embedding full records into each
         *     other's duplicate group would nest indefinitely for a larger cluster.
         *     Carries every field the frontend's duplicate comparison table needs to
         *     judge whether a match is real (urgency/provider/reason alongside the
         *     demographics), but not `duplicate_group_id`/`possible_duplicate` --
         *     those describe the peer's own membership, not this referral's.
         */
        ReferralSummary: {
            /** Id */
            id: string;
            source: components["schemas"]["ReferralSource"];
            /** Patient Name */
            patient_name: string;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Received At */
            received_at: string;
            /** Referring Provider */
            referring_provider?: string | null;
            /** Reason */
            reason?: string | null;
            urgency: components["schemas"]["Urgency"];
            status: components["schemas"]["ReferralStatus"];
        };
        /** StatusUpdateRequest */
        StatusUpdateRequest: {
            status: components["schemas"]["ReferralStatus"];
        };
        /** StatusUpdateResponse */
        StatusUpdateResponse: {
            data: components["schemas"]["Referral"];
        };
        /**
         * Urgency
         * @description One ordinal scale collapsing three source vocabularies onto it.
         *
         *     - efax:     ROUTINE -> routine, STAT -> stat
         *     - ehr_fhir: routine -> routine, urgent -> urgent, asap (or stat) -> stat
         *     - web_form: urgent=False -> routine, urgent=True -> urgent
         *                 (the boolean can never express `stat` -- a lossy mapping,
         *                 documented in the README as a duplicate/urgency failure mode)
         * @enum {string}
         */
        Urgency: "routine" | "urgent" | "stat";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_referrals_route_referrals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReferralStatus"] | null;
                source?: components["schemas"]["ReferralSource"] | null;
                urgency?: components["schemas"]["Urgency"] | null;
                q?: string | null;
                sort?: "-received_at" | "received_at";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralListResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_referral_route_referrals__referral_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralDetailResponse"];
                };
            };
            /** @description Referral not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_status_route_referrals__referral_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusUpdateResponse"];
                };
            };
            /** @description Referral not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transition not allowed by the status workflow */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
